<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        spacing: 20
        padding: 20
        Button:
            text: "Hello World!"
        Button:
            text: "Goodbye World!"
        Button:
            text: "I'm Hungry xd!"
            #width: 200
            #height: 50
            pos_hint: {'center_x': .5}
            size_hint: (1,.1)