<MyLayout>
    BoxLatout:
        orientation: 'vertical'
        size: root.widht, root.height
        padding: 10
        spacing: 10

        Label:
            text: "Name"
        TextInput:
            multiline: False
        Label:
            text: "Favorite Pizza"
        TextInput:
            multiline: False
        Button:
            text: "Submit"
        TextInput:
            multiline: False
        Button: 
            text: "Clear"